# Generated by Django 4.2.3 on 2023-10-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DP', 'En Confirmacion'), ('FS', 'Confirmada'), ('ER', 'Completada')], default='DP', max_length=20)),
            ],
        ),
    ]
