# Generated by Django 4.2.3 on 2023-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='estado',
            field=models.CharField(choices=[('DP', 'Disponible'), ('FS', 'Fuera de Servicio'), ('ER', 'En Reparacion')], default='DP', max_length=20),
        ),
    ]
