# Generated by Django 4.2.3 on 2023-11-12 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('cambiada', 'Cambiada')], default='programada', max_length=10)),
                ('especialista_primario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas2_primarias', to=settings.AUTH_USER_MODEL)),
                ('especialista_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas2_secundarias', to=settings.AUTH_USER_MODEL)),
                ('nombre_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
