# Generated by Django 4.2.3 on 2023-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita2',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
