# Generated by Django 4.2.3 on 2023-11-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0003_cita2_sala_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita2',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='cita2',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita2',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
