# Generated by Django 4.2.3 on 2023-11-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0004_remove_cita2_fecha_hora_cita2_fecha_cita2_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita2',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
