# Generated by Django 4.2.3 on 2023-11-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0005_cita2_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita2',
            name='fecha_hora',
        ),
    ]
