# Generated by Django 4.2.3 on 2023-11-15 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_alergias_paciente_cirugias_previas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cita2', '0007_remove_cita2_fecha_remove_cita2_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita2',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='cita2',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita2',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita2',
            name='especialista_primario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas2_primarias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita2',
            name='nombre_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
