# Generated by Django 4.2.3 on 2023-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0008_remove_cita2_fecha_hora_cita2_fecha_cita2_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita2',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
