# Generated by Django 4.2.3 on 2023-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0009_cita2_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita2',
            name='descripcion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
