# Generated by Django 4.2.3 on 2023-11-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0010_alter_cita2_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita2',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
