# Generated by Django 4.2.3 on 2023-11-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_codigo_medico_user_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codigo_medico',
        ),
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numero_telefono',
        ),
    ]
