# Generated by Django 4.2.3 on 2023-10-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='stock_sala',
        ),
    ]
