# Generated by Django 4.2.3 on 2023-11-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_alter_salas_estado'),
        ('insumo', '0005_alter_insumo_id_sala'),
        ('inventario', '0002_remove_inventario_stock_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salas.salas'),
        ),
    ]
