export * from "./LoginAdmin";
export * from "./HomeAdmin";
export * from "./UsersAdmin";
export * from "./SalasAdmin";
export * from "./InsumosAdmin";
export * from "./InventarioAdmin";
export * from "./DetalleInventario";
export * from "./DetalleInsumos";
export * from "./Paciente";
