# Generated by Django 4.2.3 on 2023-11-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0002_especialista_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='user',
        ),
    ]
