# Generated by Django 4.2.3 on 2023-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIn', models.CharField(max_length=50)),
                ('stockIn', models.IntegerField()),
                ('tipoIn', models.CharField(choices=[('C', 'Consuntivo'), ('NC', 'No consuntivo')], max_length=2)),
                ('precioUIn', models.IntegerField()),
                ('totalIn', models.IntegerField()),
            ],
        ),
    ]
