# Generated by Django 4.2.3 on 2023-10-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_alter_salas_estado'),
        ('insumo', '0002_alter_insumo_totalin'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='id_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salas.salas'),
        ),
    ]
