# Generated by Django 4.2.3 on 2023-11-11 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_insumo_id_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fechaIn',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
