# Generated by Django 4.2.3 on 2023-11-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0005_alter_insumo_id_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='fechaIn',
        ),
    ]
