# Generated by Django 4.2.3 on 2023-12-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0006_remove_insumo_fechain'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='descripcionIn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='marcaIn',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
