# Generated by Django 4.2.3 on 2023-11-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_historial_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='operacion',
            field=models.CharField(blank=True, choices=[('S', 'Suma'), ('R', 'Resta'), ('C', 'Cambio')], max_length=20, null=True),
        ),
    ]
