# Generated by Django 4.2.3 on 2023-11-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_historial_cantidad_alter_historial_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
