# Generated by Django 4.2.3 on 2023-11-14 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0004_insumo_fechain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salas', '0002_alter_salas_estado'),
        ('historial', '0005_alter_historial_fecha_alter_historial_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salas.salas'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
