# Generated by Django 4.2.3 on 2023-11-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0006_alter_historial_id_insumo_alter_historial_id_sala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='cantidadU',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
