# Generated by Django 4.2.3 on 2023-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0007_historial_cantidadu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
