# Generated by Django 4.2.3 on 2023-11-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita2', '0011_cita2_diagnostico'),
        ('historial', '0008_historial_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='id_cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cita2.cita2'),
        ),
    ]
